steps:
- id: "get build number"
    name: gcr.io/cloud-builders/git
    dir: 'sireesh'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']
    
 - id: "build and submit the dataflow job"
    name: maven:3.6.0-jdk-11-slim
    dir: 'sireesh'
    entrypoint: 'bash'
    args: ['./submit.sh','--DataflowPipeline']
    waitFor: ['get build number']
